      - name: Build App
        run: |
          xcodebuild clean archive \
            -scheme madari \
            -sdk iphoneos \ # Let Xcode choose the appropriate SDK
            -configuration Release \
            -archivePath $GITHUB_WORKSPACE/madari.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            SUPPORTED_PLATFORMS="iphoneos" \
            IPHONEOS_DEPLOYMENT_TARGET="16.0" # Set deployment target to iOS 16
